pol/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^poll/', include('poll.urls')),
]

poll/urls.py
from django.conf.urls import url
from . import views

app_name = 'poll';

urlpatterns = [
    #/poll/
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),

    #/poll/5/
    # url(r'^(?P<topic_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    #/poll/5/vote/
    # url(r'^(?P<topic_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<topic_id>[0-9]+)/vote/$', views.vote, name='vote'),

    #/poll/5/results/
    # url(r'^(?P<topic_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),

]

poll/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Topic(models.Model):
    topic_text  = models.CharField(max_length=150)
    pub_date    = models.DateTimeField('date added')

    def __str__(self):
        return self.topic_text

class Choice(models.Model):
    choice_text = models.CharField(max_length=150)
    topic       = models.ForeignKey(Topic, on_delete = models.CASCADE)
    votes       = models.IntegerField(default=0)
    pub_date    = models.DateTimeField('date added')

    def __str__(self):
        return self.choice_text

class Comment(models.Model):
    comment_text    = models.CharField(max_length=1000)
    type            = models.CharField(max_length=3)
    choice          = models.ForeignKey(Choice, on_delete = models.CASCADE)

poll/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404, get_list_or_404

from django.http import HttpResponseRedirect, HttpResponse

from django.urls import reverse

from django.views import generic

from .models import Topic
from .models import Choice


# Create your views here.
# def index(request):
#     all_topics = Topic.objects.all();
#
#     return render(request, "poll/index.html", {'all_topics' : all_topics})
#
# def detail(request, topic_id):
#     topic   = get_object_or_404(Topic, pk = topic_id)
#     choices =  get_list_or_404(Choice, topic_id = topic_id)
#
#     return render(request, "poll/detail.html",
#         {
#             'topic'  : topic,
#             'choices': choices
#         })
#
# def results(request, topic_id):
#     topic = get_object_or_404(Topic, pk = topic_id)
#     return render(request, 'poll/results.html', {'topic': topic})

class IndexView(generic.ListView):
    template_name = 'poll/index.html'
    context_object_name = 'topic_list'

    def get_queryset(self):
        """Return the last five published topics."""
        return Topic.objects.order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Topic
    template_name = 'poll/detail.html'


class ResultsView(generic.DetailView):
    model = Topic
    template_name = 'poll/results.html'


def vote(request, topic_id):
    topic =  get_object_or_404(Topic, pk = topic_id)
    try:
        selected_choice = topic.choice_set.get(id=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the topic voting form.
        return render(request, 'poll/detail.html', {
            'topic': topic,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('poll:results', args=(topic.id,)))

poll/templates/poll/detail.html
<h1>{{ topic.topic_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'poll:vote' topic.id %}" method="post">
{% csrf_token %}
{% for choice in topic.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

poll/templates/poll/index.html
{% if topic_list %}

<h1>Start polling!</h1>

<ul>
    {% for topic in topic_list %}
        <li><a href="{% url 'poll:detail' topic.id %}"> {{ topic.topic_text }} </a></li>
    {% endfor %}
</ul>

{% else %}
<h1>No polls yet.</h1>
{% endif %}

poll/templates/poll/results.html
<h1>{{ topic.topic_text }}</h1>

<ul>
{% for choice in topic.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'poll:detail' topic.id %}">Vote again?</a>